# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: Markdown-to-Pages Action
author: W Anders <w@doubleu.codes>
description: Turn your README(s) into a basic static site.
inputs:
  token:
    required: true
    description: A token is required to communicate with the Github API
  custom_css:
    description: Path to a custom CSS file to override Github styles.
  files:
    description: Markdown files to render
    default: README.md
  out_path:
    description: Path the rendered files will be output to
    default: dist
  out_path_not_empty:
    description: |
      Set 'true' if the output path exists and is expected to already have content
    default: 'false'
  title:
    description: |
      Title of the path (default: username/repository)
runs:
  using: node20
  main: dist/index.js
branding:
  icon: book
  color: purple
